/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    services: Service;
    leads: Lead;
    pages: Page;
    blogs: Blog;
    testimonials: Testimonial;
    faqs: Faq;
    products: Product;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    blogs: BlogsSelect<false> | BlogsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'homepage-settings': HomepageSetting;
  };
  globalsSelect: {
    'homepage-settings': HomepageSettingsSelect<false> | HomepageSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName: string;
  lastName?: string | null;
  role: 'super-admin' | 'admin' | 'editor' | 'viewer';
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  name: string;
  slug: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  hero_image?: (number | null) | Media;
  features?:
    | {
        feature?: string | null;
        id?: string | null;
      }[]
    | null;
  faqs?: (number | Faq)[] | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    canonical?: string | null;
  };
  page_builder?:
    | {
        sectionTitle?: string | null;
        sectionDescription?: string | null;
        displayMode?: ('rent' | 'buy' | 'both') | null;
        products?: (number | Product)[] | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'productGrid';
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  slug: string;
  image?: (number | null) | Media;
  /**
   * Monthly rent price in ₹ (e.g. 1499)
   */
  rentPrice?: number | null;
  /**
   * Purchase price in ₹ (e.g. 45000)
   */
  buyPrice?: number | null;
  rating?: number | null;
  ratingCount?: number | null;
  rating5Star?: number | null;
  rating4Star?: number | null;
  rating3Star?: number | null;
  rating2Star?: number | null;
  rating1Star?: number | null;
  category?: ('oxygen' | 'respiratory' | 'icu' | 'mobility' | 'monitoring' | 'other') | null;
  /**
   * Show in "Highest Selling Products" section
   */
  isFeatured?: boolean | null;
  isAvailableForRent?: boolean | null;
  isAvailableForPurchase?: boolean | null;
  /**
   * Lower numbers appear first
   */
  sortOrder?: number | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  features?:
    | {
        feature?: string | null;
        id?: string | null;
      }[]
    | null;
  faqs?: (number | Faq)[] | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    canonical?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  mobile: string;
  email?: string | null;
  /**
   * Direct relation to the Service collection
   */
  service?: (number | null) | Service;
  /**
   * Hardcoded slug to preserve history in case the service is deleted
   */
  service_slug_history: string;
  product_slug?: string | null;
  location: string;
  message?: string | null;
  source_url: string;
  utm_params?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  form_token?: string | null;
  ip_hash?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  status?: ('draft' | 'published') | null;
  publishedAt?: string | null;
  page_builder?:
    | (
        | {
            heading: string;
            subHeading?: string | null;
            primaryButtonText?: string | null;
            primaryButtonLink?: string | null;
            secondaryButtonText?: string | null;
            secondaryButtonLink?: string | null;
            backgroundImage?: (number | null) | Media;
            alignment?: ('left' | 'center' | 'right') | null;
            showStats?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            title: string;
            description?: string | null;
            buttonText?: string | null;
            buttonLink?: string | null;
            backgroundColor?: ('teal' | 'white' | 'dark') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            sectionTitle?: string | null;
            sectionDescription?: string | null;
            features?:
              | {
                  /**
                   * Lucide icon name (e.g., Check, Star, Heart)
                   */
                  icon?: string | null;
                  title: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'feature';
          }
        | {
            sectionTitle?: string | null;
            sectionDescription?: string | null;
            faqItems?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            sectionTitle?: string | null;
            testimonialItems?:
              | {
                  name: string;
                  designation?: string | null;
                  rating?: number | null;
                  photo?: (number | null) | Media;
                  review: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonial';
          }
        | {
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            sectionTitle?: string | null;
            sectionDescription?: string | null;
            displayMode?: ('rent' | 'buy' | 'both') | null;
            products?: (number | Product)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'productGrid';
          }
        | {
            sectionTitle?: string | null;
            sectionDescription?: string | null;
            steps?:
              | {
                  /**
                   * Step number (e.g. "01")
                   */
                  number: string;
                  /**
                   * Lucide icon name (e.g. Phone, MessageSquare)
                   */
                  icon?: string | null;
                  title: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'steps';
          }
        | {
            sectionTitle?: string | null;
            sectionDescription?: string | null;
            doctors?:
              | {
                  name: string;
                  qualification?: string | null;
                  experience?: string | null;
                  /**
                   * e.g. "FOUNDER" — leave empty for no badge
                   */
                  badge?: string | null;
                  image?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'doctorGrid';
          }
      )[]
    | null;
  seo?: {
    meta_title?: string | null;
    meta_description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs".
 */
export interface Blog {
  id: number;
  title: string;
  slug: string;
  featured_image?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  category?: string | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  author?: (number | null) | User;
  publish_date?: string | null;
  seo?: {
    meta_title?: string | null;
    meta_description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  type: 'written' | 'video';
  name: string;
  /**
   * Social media handle (e.g. @neha.pandey)
   */
  handle?: string | null;
  designation?: string | null;
  organization?: string | null;
  /**
   * Profile photo or video thumbnail
   */
  image?: (number | null) | Media;
  /**
   * MP4 video file for video testimonials
   */
  videoFile?: (number | null) | Media;
  rating?: number | null;
  testimonial: string;
  /**
   * Display time (e.g. "2 weeks ago", "1 month ago")
   */
  timeAgo?: string | null;
  /**
   * Link to a social media profile or post (e.g., Instagram Reel)
   */
  social_media_link?: string | null;
  /**
   * Instagram post/reel URL
   */
  instagramLink?: string | null;
  /**
   * Show verified badge next to handle
   */
  isVerified?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'blogs';
        value: number | Blog;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  hero_image?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  faqs?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonical?: T;
      };
  page_builder?:
    | T
    | {
        productGrid?:
          | T
          | {
              sectionTitle?: T;
              sectionDescription?: T;
              displayMode?: T;
              products?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  mobile?: T;
  email?: T;
  service?: T;
  service_slug_history?: T;
  product_slug?: T;
  location?: T;
  message?: T;
  source_url?: T;
  utm_params?: T;
  form_token?: T;
  ip_hash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  publishedAt?: T;
  page_builder?:
    | T
    | {
        hero?:
          | T
          | {
              heading?: T;
              subHeading?: T;
              primaryButtonText?: T;
              primaryButtonLink?: T;
              secondaryButtonText?: T;
              secondaryButtonLink?: T;
              backgroundImage?: T;
              alignment?: T;
              showStats?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              title?: T;
              description?: T;
              buttonText?: T;
              buttonLink?: T;
              backgroundColor?: T;
              id?: T;
              blockName?: T;
            };
        feature?:
          | T
          | {
              sectionTitle?: T;
              sectionDescription?: T;
              features?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              sectionTitle?: T;
              sectionDescription?: T;
              faqItems?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonial?:
          | T
          | {
              sectionTitle?: T;
              testimonialItems?:
                | T
                | {
                    name?: T;
                    designation?: T;
                    rating?: T;
                    photo?: T;
                    review?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        productGrid?:
          | T
          | {
              sectionTitle?: T;
              sectionDescription?: T;
              displayMode?: T;
              products?: T;
              id?: T;
              blockName?: T;
            };
        steps?:
          | T
          | {
              sectionTitle?: T;
              sectionDescription?: T;
              steps?:
                | T
                | {
                    number?: T;
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        doctorGrid?:
          | T
          | {
              sectionTitle?: T;
              sectionDescription?: T;
              doctors?:
                | T
                | {
                    name?: T;
                    qualification?: T;
                    experience?: T;
                    badge?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        meta_title?: T;
        meta_description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs_select".
 */
export interface BlogsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  featured_image?: T;
  content?: T;
  category?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  author?: T;
  publish_date?: T;
  seo?:
    | T
    | {
        meta_title?: T;
        meta_description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  type?: T;
  name?: T;
  handle?: T;
  designation?: T;
  organization?: T;
  image?: T;
  videoFile?: T;
  rating?: T;
  testimonial?: T;
  timeAgo?: T;
  social_media_link?: T;
  instagramLink?: T;
  isVerified?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  image?: T;
  rentPrice?: T;
  buyPrice?: T;
  rating?: T;
  ratingCount?: T;
  rating5Star?: T;
  rating4Star?: T;
  rating3Star?: T;
  rating2Star?: T;
  rating1Star?: T;
  category?: T;
  isFeatured?: T;
  isAvailableForRent?: T;
  isAvailableForPurchase?: T;
  sortOrder?: T;
  description?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  faqs?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonical?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-settings".
 */
export interface HomepageSetting {
  id: number;
  heroSlides?:
    | {
        /**
         * e.g. "LIMITED PERIOD OFFER"
         */
        badge?: string | null;
        heading: string;
        bullets?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        ctaText?: string | null;
        ctaHref?: string | null;
        image?: (number | null) | Media;
        /**
         * Top line of quality badge (e.g. "BEST QUALITY")
         */
        qualityBadgeLine1?: string | null;
        /**
         * Bottom line of quality badge (e.g. "BEST PRICE")
         */
        qualityBadgeLine2?: string | null;
        id?: string | null;
      }[]
    | null;
  healthcareIntro?: {
    heading?: string | null;
    description?: string | null;
  };
  serviceCategories?:
    | {
        title: string;
        /**
         * e.g. "X-ray, ECG, Blood Investigations"
         */
        subtitle?: string | null;
        image?: (number | null) | Media;
        href: string;
        id?: string | null;
      }[]
    | null;
  trustBadges?:
    | {
        /**
         * Lucide icon name (e.g. UserCheck, Users, Headphones, ShieldCheck)
         */
        icon?: string | null;
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  problemsSection?: {
    heading?: string | null;
    description?: string | null;
    problems?:
      | {
          /**
           * Lucide icon name (e.g. Wind, Building2, HeartPulse, Activity)
           */
          icon?: string | null;
          title: string;
          id?: string | null;
        }[]
      | null;
  };
  highestSellingSection?: {
    heading?: string | null;
    description?: string | null;
  };
  rentOrBuySection?: {
    heading?: string | null;
    description?: string | null;
    rentBenefits?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    buyBenefits?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  expertDoctorsSection?: {
    heading?: string | null;
    description?: string | null;
    doctors?:
      | {
          name: string;
          qualification?: string | null;
          experience?: string | null;
          /**
           * e.g. "FOUNDER" — leave empty for no badge
           */
          badge?: string | null;
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  testimonialsSection?: {
    heading?: string | null;
    description?: string | null;
  };
  beforeAfterSection?: {
    heading?: string | null;
    description?: string | null;
    stories?:
      | {
          patientName: string;
          age?: number | null;
          condition?: string | null;
          quote?: string | null;
          beforeImage?: (number | null) | Media;
          afterImage?: (number | null) | Media;
          /**
           * Patient portrait photo
           */
          patientImage?: (number | null) | Media;
          fullStoryLink?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  ourStorySection?: {
    heading?: string | null;
    /**
     * The story paragraphs on the left side
     */
    narrative?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    team?:
      | {
          name: string;
          role?: string | null;
          image?: (number | null) | Media;
          badges?:
            | {
                label: string;
                id?: string | null;
              }[]
            | null;
          education?:
            | {
                text: string;
                id?: string | null;
              }[]
            | null;
          experience?:
            | {
                text: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  blogsSection?: {
    heading?: string | null;
    description?: string | null;
  };
  howItWorksSection?: {
    heading?: string | null;
    description?: string | null;
    steps?:
      | {
          /**
           * e.g. "01"
           */
          number: string;
          /**
           * Lucide icon name (e.g. Phone, MessageSquare, Truck, HeartHandshake)
           */
          icon?: string | null;
          title: string;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  locationSection?: {
    heading?: string | null;
    companyName?: string | null;
    address?: string | null;
    /**
     * Google Maps embed URL
     */
    mapEmbedUrl?: string | null;
    getDirectionsLink?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-settings_select".
 */
export interface HomepageSettingsSelect<T extends boolean = true> {
  heroSlides?:
    | T
    | {
        badge?: T;
        heading?: T;
        bullets?:
          | T
          | {
              text?: T;
              id?: T;
            };
        ctaText?: T;
        ctaHref?: T;
        image?: T;
        qualityBadgeLine1?: T;
        qualityBadgeLine2?: T;
        id?: T;
      };
  healthcareIntro?:
    | T
    | {
        heading?: T;
        description?: T;
      };
  serviceCategories?:
    | T
    | {
        title?: T;
        subtitle?: T;
        image?: T;
        href?: T;
        id?: T;
      };
  trustBadges?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  problemsSection?:
    | T
    | {
        heading?: T;
        description?: T;
        problems?:
          | T
          | {
              icon?: T;
              title?: T;
              id?: T;
            };
      };
  highestSellingSection?:
    | T
    | {
        heading?: T;
        description?: T;
      };
  rentOrBuySection?:
    | T
    | {
        heading?: T;
        description?: T;
        rentBenefits?:
          | T
          | {
              text?: T;
              id?: T;
            };
        buyBenefits?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  expertDoctorsSection?:
    | T
    | {
        heading?: T;
        description?: T;
        doctors?:
          | T
          | {
              name?: T;
              qualification?: T;
              experience?: T;
              badge?: T;
              image?: T;
              id?: T;
            };
      };
  testimonialsSection?:
    | T
    | {
        heading?: T;
        description?: T;
      };
  beforeAfterSection?:
    | T
    | {
        heading?: T;
        description?: T;
        stories?:
          | T
          | {
              patientName?: T;
              age?: T;
              condition?: T;
              quote?: T;
              beforeImage?: T;
              afterImage?: T;
              patientImage?: T;
              fullStoryLink?: T;
              id?: T;
            };
      };
  ourStorySection?:
    | T
    | {
        heading?: T;
        narrative?: T;
        team?:
          | T
          | {
              name?: T;
              role?: T;
              image?: T;
              badges?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              education?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              experience?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  blogsSection?:
    | T
    | {
        heading?: T;
        description?: T;
      };
  howItWorksSection?:
    | T
    | {
        heading?: T;
        description?: T;
        steps?:
          | T
          | {
              number?: T;
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  locationSection?:
    | T
    | {
        heading?: T;
        companyName?: T;
        address?: T;
        mapEmbedUrl?: T;
        getDirectionsLink?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}